export type Product = {
  id: string
  name: string
  description: string
  price: number
  unit: string
  image: string
  category: string
  region: string
  country: string
  farmName: string
  farmerId: string
  organic: boolean
  featured?: boolean
  inStock: boolean
  rating: number
  reviews: number
  tags: string[]
  certifications: string[]
}

export const africanProducts: Product[] = [
  {
    id: "af001",
    name: "Premium Ethiopian Coffee Beans",
    description:
      "Hand-picked Arabica coffee beans from the highlands of Ethiopia. These beans are grown at high altitude, producing a complex flavor profile with notes of blueberry, dark chocolate, and citrus.",
    price: 12.99,
    unit: "500g",
    image: "/placeholder.svg?height=300&width=300&text=Ethiopian+Coffee",
    category: "Coffee & Tea",
    region: "East Africa",
    country: "Ethiopia",
    farmName: "Yirgacheffe Cooperative",
    farmerId: "ETH-001",
    organic: true,
    featured: true,
    inStock: true,
    rating: 4.8,
    reviews: 124,
    tags: ["Coffee", "Arabica", "Fair Trade"],
    certifications: ["Organic", "Fair Trade", "Rainforest Alliance"],
  },
  {
    id: "af002",
    name: "Ghanaian Raw Cocoa Beans",
    description:
      "Premium unprocessed cocoa beans from Ghana's fertile cocoa-growing regions. Known for their rich, intense chocolate flavor and aromatic qualities.",
    price: 14.5,
    unit: "1kg",
    image: "/placeholder.svg?height=300&width=300&text=Ghanaian+Cocoa",
    category: "Cocoa & Chocolate",
    region: "West Africa",
    country: "Ghana",
    farmName: "Kuapa Kokoo Cooperative",
    farmerId: "GHA-002",
    organic: true,
    inStock: true,
    rating: 4.7,
    reviews: 89,
    tags: ["Cocoa", "Chocolate", "Baking"],
    certifications: ["Fair Trade", "UTZ Certified"],
  },
  {
    id: "af003",
    name: "Kenyan Purple Tea",
    description:
      "Rare purple tea from the highlands of Kenya. Rich in anthocyanins with a delicate flavor and subtle sweet notes. Known for its health benefits and unique color.",
    price: 18.99,
    unit: "100g",
    image: "/placeholder.svg?height=300&width=300&text=Kenyan+Purple+Tea",
    category: "Coffee & Tea",
    region: "East Africa",
    country: "Kenya",
    farmName: "Nandi Hills Estate",
    farmerId: "KEN-003",
    organic: true,
    inStock: true,
    rating: 4.6,
    reviews: 42,
    tags: ["Tea", "Purple Tea", "Specialty"],
    certifications: ["Organic", "Kenya Tea Development Agency"],
  },
  {
    id: "af004",
    name: "Nigerian Shea Butter",
    description:
      "Raw, unrefined shea butter hand-processed by women's cooperatives in Nigeria. Perfect for skincare, haircare, and culinary uses.",
    price: 9.99,
    unit: "250g",
    image: "/placeholder.svg?height=300&width=300&text=Nigerian+Shea+Butter",
    category: "Natural Products",
    region: "West Africa",
    country: "Nigeria",
    farmName: "Women's Shea Collective",
    farmerId: "NIG-004",
    organic: true,
    inStock: true,
    rating: 4.9,
    reviews: 156,
    tags: ["Shea Butter", "Skincare", "Natural"],
    certifications: ["Organic", "Fair Trade"],
  },
  {
    id: "af005",
    name: "Moroccan Argan Oil",
    description:
      "Cold-pressed argan oil from the Argania spinosa trees of Morocco. Traditionally harvested and processed by Berber women's cooperatives.",
    price: 24.99,
    unit: "100ml",
    image: "/placeholder.svg?height=300&width=300&text=Moroccan+Argan+Oil",
    category: "Natural Products",
    region: "North Africa",
    country: "Morocco",
    farmName: "Atlas Mountains Cooperative",
    farmerId: "MOR-005",
    organic: true,
    inStock: true,
    rating: 4.8,
    reviews: 112,
    tags: ["Argan Oil", "Skincare", "Culinary"],
    certifications: ["Organic", "Ecocert"],
  },
  {
    id: "af006",
    name: "South African Rooibos Tea",
    description:
      "Naturally caffeine-free herbal tea from the Cederberg region of South Africa. Known for its sweet, nutty flavor and numerous health benefits.",
    price: 8.5,
    unit: "200g",
    image: "/placeholder.svg?height=300&width=300&text=Rooibos+Tea",
    category: "Coffee & Tea",
    region: "Southern Africa",
    country: "South Africa",
    farmName: "Cederberg Cooperative",
    farmerId: "RSA-006",
    organic: true,
    inStock: true,
    rating: 4.7,
    reviews: 98,
    tags: ["Tea", "Herbal", "Caffeine-free"],
    certifications: ["Organic", "Fair Trade"],
  },
  {
    id: "af007",
    name: "Tanzanian Vanilla Beans",
    description:
      "Premium grade A vanilla beans grown in the fertile soils of Tanzania. Known for their rich aroma and high vanillin content.",
    price: 29.99,
    unit: "10 pods",
    image: "/placeholder.svg?height=300&width=300&text=Tanzanian+Vanilla",
    category: "Spices",
    region: "East Africa",
    country: "Tanzania",
    farmName: "Kilimanjaro Vanilla Growers",
    farmerId: "TZA-007",
    organic: true,
    inStock: false,
    rating: 4.9,
    reviews: 67,
    tags: ["Vanilla", "Baking", "Gourmet"],
    certifications: ["Organic", "Fair Trade"],
  },
  {
    id: "af008",
    name: "Ugandan Red Chilies",
    description:
      "Sun-dried red chilies from Uganda with a balanced heat and rich flavor. Perfect for adding spice to any dish.",
    price: 6.99,
    unit: "100g",
    image: "/placeholder.svg?height=300&width=300&text=Ugandan+Chilies",
    category: "Spices",
    region: "East Africa",
    country: "Uganda",
    farmName: "Kampala Spice Farmers",
    farmerId: "UGA-008",
    organic: true,
    inStock: true,
    rating: 4.5,
    reviews: 38,
    tags: ["Chilies", "Spicy", "Cooking"],
    certifications: ["Organic"],
  },
  {
    id: "af009",
    name: "Malian Dried Hibiscus Flowers",
    description:
      "Vibrant dried hibiscus flowers (bissap) from Mali. Used to make refreshing teas, syrups, and traditional beverages throughout West Africa.",
    price: 7.5,
    unit: "150g",
    image: "/placeholder.svg?height=300&width=300&text=Hibiscus+Flowers",
    category: "Herbs & Flowers",
    region: "West Africa",
    country: "Mali",
    farmName: "Sikasso Women's Cooperative",
    farmerId: "MLI-009",
    organic: true,
    inStock: true,
    rating: 4.6,
    reviews: 52,
    tags: ["Hibiscus", "Tea", "Natural"],
    certifications: ["Organic", "Fair Trade"],
  },
  {
    id: "af010",
    name: "Rwandan Red Bourbon Coffee",
    description:
      "Single-origin Red Bourbon coffee beans from Rwanda's high-altitude regions. Features bright acidity with notes of citrus, caramel, and spice.",
    price: 13.99,
    unit: "250g",
    image: "/placeholder.svg?height=300&width=300&text=Rwandan+Coffee",
    category: "Coffee & Tea",
    region: "East Africa",
    country: "Rwanda",
    farmName: "Abakundakawa Cooperative",
    farmerId: "RWA-010",
    organic: true,
    inStock: true,
    rating: 4.8,
    reviews: 76,
    tags: ["Coffee", "Single Origin", "Specialty"],
    certifications: ["Organic", "Fair Trade", "Rainforest Alliance"],
  },
  {
    id: "af011",
    name: "Egyptian Medjool Dates",
    description:
      "Large, sweet and succulent Medjool dates from Egyptian oases. Known as the 'king of dates' for their exceptional size and caramel-like taste.",
    price: 11.99,
    unit: "500g",
    image: "/placeholder.svg?height=300&width=300&text=Egyptian+Dates",
    category: "Fruits",
    region: "North Africa",
    country: "Egypt",
    farmName: "Siwa Oasis Farms",
    farmerId: "EGY-011",
    organic: true,
    inStock: true,
    rating: 4.7,
    reviews: 93,
    tags: ["Dates", "Dried Fruit", "Natural Sweetener"],
    certifications: ["Organic"],
  },
  {
    id: "af012",
    name: "Senegalese Baobab Powder",
    description:
      "Nutrient-rich powder made from the fruit of the iconic African baobab tree. High in vitamin C, calcium, and antioxidants.",
    price: 15.99,
    unit: "200g",
    image: "/placeholder.svg?height=300&width=300&text=Baobab+Powder",
    category: "Superfoods",
    region: "West Africa",
    country: "Senegal",
    farmName: "Fatick Region Cooperative",
    farmerId: "SEN-012",
    organic: true,
    inStock: true,
    rating: 4.6,
    reviews: 48,
    tags: ["Baobab", "Superfood", "Nutritional"],
    certifications: ["Organic", "Wild Harvested"],
  },
  {
    id: "af013",
    name: "Ivorian Raw Cashew Nuts",
    description:
      "Unprocessed cashew nuts from Côte d'Ivoire, one of the world's leading producers. Perfect for roasting at home or using in cooking.",
    price: 12.5,
    unit: "500g",
    image: "/placeholder.svg?height=300&width=300&text=Ivorian+Cashews",
    category: "Nuts & Seeds",
    region: "West Africa",
    country: "Côte d'Ivoire",
    farmName: "Korhogo Cashew Collective",
    farmerId: "CIV-013",
    organic: false,
    inStock: true,
    rating: 4.5,
    reviews: 62,
    tags: ["Cashews", "Nuts", "Raw"],
    certifications: ["Fair Trade"],
  },
  {
    id: "af014",
    name: "Madagascan Bourbon Vanilla Extract",
    description:
      "Pure vanilla extract made from Madagascar's prized Bourbon vanilla beans. Rich, creamy flavor with hints of caramel and chocolate.",
    price: 19.99,
    unit: "100ml",
    image: "/placeholder.svg?height=300&width=300&text=Vanilla+Extract",
    category: "Spices",
    region: "East Africa",
    country: "Madagascar",
    farmName: "Sava Region Growers",
    farmerId: "MDG-014",
    organic: true,
    inStock: true,
    rating: 4.9,
    reviews: 105,
    tags: ["Vanilla", "Extract", "Baking"],
    certifications: ["Organic", "Fair Trade"],
  },
  {
    id: "af015",
    name: "Tunisian Deglet Noor Dates",
    description:
      "Semi-dry, translucent dates known as 'Fingers of Light' for their amber color when held to the sun. Sweet with a delicate flavor.",
    price: 9.99,
    unit: "500g",
    image: "/placeholder.svg?height=300&width=300&text=Tunisian+Dates",
    category: "Fruits",
    region: "North Africa",
    country: "Tunisia",
    farmName: "Tozeur Oasis Collective",
    farmerId: "TUN-015",
    organic: true,
    inStock: true,
    rating: 4.6,
    reviews: 57,
    tags: ["Dates", "Dried Fruit", "Snack"],
    certifications: ["Organic"],
  },
  {
    id: "af016",
    name: "Nigerian Ginger Root",
    description:
      "Aromatic, fiery ginger from Nigeria, known for its exceptional potency and flavor. Perfect for cooking, teas, and medicinal uses.",
    price: 8.99,
    unit: "250g",
    image: "/placeholder.svg?height=300&width=300&text=Nigerian+Ginger",
    category: "Spices",
    region: "West Africa",
    country: "Nigeria",
    farmName: "Kaduna Spice Farmers",
    farmerId: "NIG-016",
    organic: false,
    inStock: true,
    rating: 4.7,
    reviews: 43,
    tags: ["Ginger", "Spice", "Root"],
    certifications: [],
  },
  {
    id: "af017",
    name: "Mozambican Cashew Butter",
    description:
      "Creamy, stone-ground cashew butter made from Mozambican cashews. No additives or preservatives - just pure, nutritious cashew goodness.",
    price: 13.99,
    unit: "250g",
    image: "/placeholder.svg?height=300&width=300&text=Cashew+Butter",
    category: "Nuts & Seeds",
    region: "Southern Africa",
    country: "Mozambique",
    farmName: "Nampula Cashew Association",
    farmerId: "MOZ-017",
    organic: true,
    inStock: true,
    rating: 4.8,
    reviews: 68,
    tags: ["Cashew Butter", "Spread", "Protein"],
    certifications: ["Organic", "Fair Trade"],
  },
  {
    id: "af018",
    name: "Cameroonian Black Pepper",
    description:
      "Bold, aromatic black pepper berries from the volcanic soils of Cameroon. Known for their complex flavor with fruity and woody notes.",
    price: 7.99,
    unit: "100g",
    image: "/placeholder.svg?height=300&width=300&text=Black+Pepper",
    category: "Spices",
    region: "Central Africa",
    country: "Cameroon",
    farmName: "Mount Cameroon Spice Growers",
    farmerId: "CMR-018",
    organic: true,
    inStock: true,
    rating: 4.6,
    reviews: 39,
    tags: ["Pepper", "Spice", "Seasoning"],
    certifications: ["Organic"],
  },
  {
    id: "af019",
    name: "Zambian Wild Honey",
    description:
      "Raw, unfiltered honey harvested from wild beehives in Zambia's pristine forests. Rich amber color with complex floral notes.",
    price: 16.99,
    unit: "350g",
    image: "/placeholder.svg?height=300&width=300&text=Zambian+Honey",
    category: "Natural Products",
    region: "Southern Africa",
    country: "Zambia",
    farmName: "North Luangwa Honey Harvesters",
    farmerId: "ZMB-019",
    organic: true,
    inStock: true,
    rating: 4.9,
    reviews: 82,
    tags: ["Honey", "Wild", "Raw"],
    certifications: ["Organic", "Wild Harvested"],
  },
  {
    id: "af020",
    name: "Algerian Deglet Noor Dates",
    description:
      "Premium dates from Algeria's desert oases. Semi-dry with a mild, sweet flavor and firm texture, perfect for snacking or cooking.",
    price: 10.5,
    unit: "500g",
    image: "/placeholder.svg?height=300&width=300&text=Algerian+Dates",
    category: "Fruits",
    region: "North Africa",
    country: "Algeria",
    farmName: "Biskra Oasis Cooperative",
    farmerId: "DZA-020",
    organic: false,
    inStock: true,
    rating: 4.5,
    reviews: 47,
    tags: ["Dates", "Dried Fruit", "Natural Sweetener"],
    certifications: [],
  },
]

export const productCategories = [
  "Coffee & Tea",
  "Cocoa & Chocolate",
  "Spices",
  "Natural Products",
  "Fruits",
  "Nuts & Seeds",
  "Herbs & Flowers",
  "Superfoods",
]

export const regions = ["North Africa", "East Africa", "West Africa", "Central Africa", "Southern Africa"]

export const certifications = [
  "Organic",
  "Fair Trade",
  "Rainforest Alliance",
  "UTZ Certified",
  "Wild Harvested",
  "Ecocert",
]
